#!/bin/bash
#UUID=$(curl -sL https://www.uuidgenerator.net/api/version4)
#UUID2=$(curl -sL https://www.uuidgenerator.net/api/version4)
#CLEAN=${UUID//[^a-zA-Z0-9_-]/}
#CLEAN2=${UUID2//[^a-zA-Z0-9_-]/}
CLEAN=$(uuidgen -r)
CLEAN2=$(uuidgen -r)
OPTIND=1         # Reset in case getopts has been used previously in the shell.

# Initialize our own variables:

verbose=0

while getopts ":m:i:s:p:j:o:d:" opt; do
    case $opt in
		h|\?)
			echo "This tool expects you to use SSL, all args must be there or else the something is missing in the config"
			echo "This is REALLY, REALLY, REALLY, badly made"
			echo "	-m, persons initals"
  		echo "	-f, Output file (Default, EMAIL.mobileconfig)"
			echo "	-s, Use SSL (true, false)"
			exit 0
				;;
    m)
				INI=$OPTARG
        EMAIL=$OPTARG"@coworkingplus.dk"
				output_file=$EMAIL".mobileconfig"
        ;;
		s)	SSL=$OPTARG
				;;
    f)  output_file=$OPTARG
        ;;
    esac
done
SSL=false
IDENTIFIER=$EMAIL
SMTP="asmtp.curanet.dk"
SMTP_PORT="587"
ORG="coworkingplus.dk"
IMAP="mail16.123hotel.dk"
IMAP_PORT="143"

touch $output_file

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
  <key>PayloadContent</key>
  <array>
    <dict>
      <key>EmailAccountDescription</key>
      <string>$EMAIL</string>
      <key>EmailAccountName</key>
      <string>$EMAIL</string>
      <key>EmailAccountType</key>
      <string>EmailTypeIMAP</string>
      <key>EmailAddress</key>
      <string>$EMAIL</string>
      <key>IncomingMailServerAuthentication</key>
      <string>EmailAuthPassword</string>
      <key>IncomingMailServerHostName</key>
      <string>$IMAP</string>
      <key>IncomingMailServerPortNumber</key>
      <integer>$IMAP_PORT</integer>
      <key>IncomingMailServerUseSSL</key>
      <$SSL/>
      <key>IncomingMailServerUsername</key>
      <string>$EMAIL</string>
      <key>OutgoingMailServerAuthentication</key>
      <string>EmailAuthPassword</string>
      <key>OutgoingMailServerHostName</key>
      <string>$SMTP</string>
      <key>OutgoingMailServerPortNumber</key>
      <integer>$SMTP_PORT</integer>
      <key>OutgoingMailServerUseSSL</key>
      <$SSL/>
      <key>OutgoingMailServerUsername</key>
      <string>$EMAIL</string>
      <key>OutgoingPasswordSameAsIncomingPassword</key>
      <true/>
      <key>PayloadDescription</key>
      <string>$EMAIL Secure Email Setup</string>
      <key>PayloadDisplayName</key>
      <string>$EMAIL Secure Email Setup</string>
      <key>PayloadIdentifier</key>
      <string>mail.org.ss.coworkingplus.dk</string>
      <key>PayloadOrganization</key>
      <string>$ORG</string>
      <key>PayloadType</key>
      <string>com.apple.mail.managed</string>
      <key>PayloadUUID</key>
      <string>$CLEAN</string>
      <key>PayloadVersion</key>
      <integer>1</integer>
      <key>PreventAppSheet</key>
      <false/>
      <key>PreventMove</key>
      <false/>
      <key>SMIMEEnabled</key>
      <false/>
      <key>IncomingMailServerIMAPPathPrefix</key>
      <string></string>
    </dict>
  </array>
	<key>PayloadDescription</key>
	<string>$EMAIL Secure Email Setup</string>
	<key>PayloadDisplayName</key>
	<string>$EMAIL Secure Email Setup</string>
	<key>PayloadIdentifier</key>
	<string>mail.org.$INI.coworkingodense.dk</string>
	<key>PayloadOrganization</key>
	<string>mail.org.$INI.coworkingodense.dk</string>
	<key>PayloadRemovalDisallowed</key>
	<false/>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>$CLEAN2</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>" > $output_file
