return {
  --  'pmizio/typescript-tools.nvim',
  --  dependencies = { 'nvim-lua/plenary.nvim', 'neovim/nvim-lspconfig' },
  --  opts = {
  --    settings = {
  --      tsserver_file_preferences = {
  --        includeInlayParameterNameHints = 'all',
  --        includeInlayParameterNameHintsWhenArgumentMatchesName = false,
  --        includeInlayFunctionParameterTypeHints = true,
  --        includeInlayVariableTypeHints = true,
  --        includeInlayPropertyDeclarationTypeHints = true,
  --        includeInlayFunctionLikeReturnTypeHints = true,
  --        includeInlayEnumMemberValueHints = true,
  --      },
  --      tsserver_format_options = {
  --        insertSpaceAfterCommaDelimiter = true,
  --        insertSpaceAfterSemicolonInForStatements = true,
  --        insertSpaceBeforeAndAfterBinaryOperators = true,
  --        insertSpaceAfterKeywordsInControlFlowStatements = true,
  --        insertSpaceAfterFunctionKeywordForAnonymousFunctions = true,
  --        insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis = false,
  --        insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets = false,
  --        insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces = false,
  --        placeOpenBraceOnNewLineForFunctions = false,
  --        placeOpenBraceOnNewLineForControlBlocks = false,
  --        convertTabsToSpaces = true,
  --        tabSize = 2,
  --        indentSize = 2,
  --      },
  --    },
  --  },
}
